version: '3.5'
services:
  db:
    container_name: db
    image: percona:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - percona8:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
  webserver:
    container_name: webserver
    build: .
    volumes:
      - ../src:/var/www/html
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    restart: always
#    Uncomment two following lines on linux and append with your host main IP to enable Xdebug
#    extra_hosts:
#      - "host.docker.internal:192.168.0.100"
volumes:
  percona8:
